sudo: required
language: node_js
node_js:
  - 10.14.2
services:
  - docker
before_install:
  # install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  # login to registry and heroku registry
  - docker login $REGISTRY_URL -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD
  - docker login -u $HEROKU_USERNAME -p $HEROKU_PASSWORD registry.heroku.com
install:
  # install deps
  - npm install
script:
  # build docker images
  - docker build -t $REGISTRY_URL/$REGISTRY_USERNAME/$REGISTRY_REPOSITORY_NAME .
deploy:
  provider: script
  script:
    # push to registry
    docker push $REGISTRY_URL/$REGISTRY_USERNAME/$REGISTRY_REPOSITORY_NAME;
  branch: master
