sudo: required
language: node_js
node_js:
  - 10.14.2
services:
  - docker
before_install:
  # login to heroku registries
  - docker login --username=$HEROKU_USERNAME --password=$HEROKU_PASSWORD registry.heroku.com
install:
  # install deps
  - npm install
script:
  # build docker images
  - docker build -t ivanmlaborda/express-travis-docker-heroku .
deploy:
  provider: script
  script:
    # push to dockerhub
    docker push ivanmlaborda/express-travis-docker-heroku;
  branch: master
