sudo: required
language: node_js
node_js:
  - 10.14.2
services:
  - docker
before_install:
  - docker login $REGISTRY_LOGIN_URL -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD
install:
  # install deps
  - npm install
script:
  # build docker images
  - docker build -t pkg-express-travis-docker-heroku:latest .
deploy:
  provider: script
  script:
    # push to registry
    docker push pkg-express-travis-docker-heroku:latest;
  branch: master
